In [1]:
import numpy as np

In [2]:
np.zeros((5,5,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [3]:
a = np.linspace(10,50,100)

In [4]:
a

array([10.        , 10.4040404 , 10.80808081, 11.21212121, 11.61616162,
       12.02020202, 12.42424242, 12.82828283, 13.23232323, 13.63636364,
       14.04040404, 14.44444444, 14.84848485, 15.25252525, 15.65656566,
       16.06060606, 16.46464646, 16.86868687, 17.27272727, 17.67676768,
       18.08080808, 18.48484848, 18.88888889, 19.29292929, 19.6969697 ,
       20.1010101 , 20.50505051, 20.90909091, 21.31313131, 21.71717172,
       22.12121212, 22.52525253, 22.92929293, 23.33333333, 23.73737374,
       24.14141414, 24.54545455, 24.94949495, 25.35353535, 25.75757576,
       26.16161616, 26.56565657, 26.96969697, 27.37373737, 27.77777778,
       28.18181818, 28.58585859, 28.98989899, 29.39393939, 29.7979798 ,
       30.2020202 , 30.60606061, 31.01010101, 31.41414141, 31.81818182,
       32.22222222, 32.62626263, 33.03030303, 33.43434343, 33.83838384,
       34.24242424, 34.64646465, 35.05050505, 35.45454545, 35.85858586,
       36.26262626, 36.66666667, 37.07070707, 37.47474747, 37.87

In [5]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [8]:
np.random.rand(5,5,5)

array([[[0.88847859, 0.09299018, 0.29192731, 0.96344916, 0.8397223 ],
        [0.42087606, 0.81334807, 0.7667328 , 0.46857801, 0.37654251],
        [0.19522743, 0.41090943, 0.31354045, 0.44278429, 0.84310179],
        [0.6778489 , 0.89337267, 0.33573599, 0.08386929, 0.32686594],
        [0.18346694, 0.78443561, 0.52529507, 0.95206066, 0.28634596]],

       [[0.80598338, 0.24925136, 0.22039913, 0.91895309, 0.58941165],
        [0.83868042, 0.86699874, 0.15690422, 0.66726473, 0.38394837],
        [0.70877634, 0.60969345, 0.96398039, 0.93701977, 0.21167566],
        [0.29126043, 0.99030683, 0.57181052, 0.78854123, 0.72366632],
        [0.53562558, 0.32666558, 0.8120891 , 0.82162088, 0.46646444]],

       [[0.41867363, 0.92092598, 0.23542739, 0.97554451, 0.78979135],
        [0.97635708, 0.74929707, 0.48471646, 0.20302861, 0.0893991 ],
        [0.87094869, 0.31805877, 0.57703423, 0.46297448, 0.20135036],
        [0.04052192, 0.18845664, 0.1194436 , 0.36642725, 0.53673885],
        [0.26425

In [16]:
a = np.random.randint(1, 10, (10, 10))

In [18]:
a[a>5]

array([8, 6, 6, 6, 6, 8, 8, 7, 7, 7, 6, 7, 8, 9, 7, 8, 7, 6, 7, 9, 7, 7,
       8, 7, 6, 7, 9, 8, 9, 8, 7, 8, 7, 8, 6, 6, 8, 7, 8, 8, 6, 6, 6, 6,
       6])