In [1]:
import numpy as np

In [3]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [4]:
a = np.array(my_list)
a

array([1, 2, 3])

In [5]:
my_list * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [7]:
a + 3

array([4, 5, 6])

In [8]:
[i+3 for i in my_list]

[4, 5, 6]

In [10]:
a = np.array([[1,4,7],[10,15,20],[7,8,9]])
a

array([[ 1,  4,  7],
       [10, 15, 20],
       [ 7,  8,  9]])

In [14]:
r = np.arange(1,11)
r

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
zeros = np.zeros(10)
ones = np.ones(10)
zeros,ones

(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]))

In [20]:
zeros = np.zeros((5,4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
a = np.linspace(10,50,100)
a

array([10.        , 10.4040404 , 10.80808081, 11.21212121, 11.61616162,
       12.02020202, 12.42424242, 12.82828283, 13.23232323, 13.63636364,
       14.04040404, 14.44444444, 14.84848485, 15.25252525, 15.65656566,
       16.06060606, 16.46464646, 16.86868687, 17.27272727, 17.67676768,
       18.08080808, 18.48484848, 18.88888889, 19.29292929, 19.6969697 ,
       20.1010101 , 20.50505051, 20.90909091, 21.31313131, 21.71717172,
       22.12121212, 22.52525253, 22.92929293, 23.33333333, 23.73737374,
       24.14141414, 24.54545455, 24.94949495, 25.35353535, 25.75757576,
       26.16161616, 26.56565657, 26.96969697, 27.37373737, 27.77777778,
       28.18181818, 28.58585859, 28.98989899, 29.39393939, 29.7979798 ,
       30.2020202 , 30.60606061, 31.01010101, 31.41414141, 31.81818182,
       32.22222222, 32.62626263, 33.03030303, 33.43434343, 33.83838384,
       34.24242424, 34.64646465, 35.05050505, 35.45454545, 35.85858586,
       36.26262626, 36.66666667, 37.07070707, 37.47474747, 37.87

In [24]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
np.random.rand(10)

array([0.38169274, 0.55998789, 0.14685671, 0.92244757, 0.54228575,
       0.30800643, 0.87918012, 0.56991577, 0.05421196, 0.31022564])

In [27]:
np.random.rand(5,5)

array([[0.39845603, 0.40714418, 0.82459031, 0.20843094, 0.76741783],
       [0.46338066, 0.47522464, 0.29521194, 0.02580707, 0.81288524],
       [0.72629735, 0.58313778, 0.31371817, 0.34231187, 0.49649741],
       [0.67511523, 0.11414881, 0.00986681, 0.33000685, 0.18077411],
       [0.51771791, 0.8819642 , 0.20951266, 0.76843847, 0.29134293]])

In [40]:
a = np.random.randint(1,10,(5,4))

In [41]:
a

array([[3, 7, 3, 5],
       [8, 4, 9, 3],
       [4, 2, 1, 9],
       [3, 9, 8, 9],
       [3, 8, 6, 1]])

In [71]:
q1 = np.random.rand(5,4)
q1

array([[0.92367514, 0.98537991, 0.92478601, 0.49088781],
       [0.97431609, 0.69345607, 0.3586684 , 0.33951068],
       [0.52281072, 0.59919183, 0.48338176, 0.4311844 ],
       [0.60681955, 0.70239426, 0.06890101, 0.86017059],
       [0.29248975, 0.45228854, 0.67307089, 0.3382637 ]])

In [73]:
q2 = q1.reshape(4,5)
q2

array([[0.92367514, 0.98537991, 0.92478601, 0.49088781, 0.97431609],
       [0.69345607, 0.3586684 , 0.33951068, 0.52281072, 0.59919183],
       [0.48338176, 0.4311844 , 0.60681955, 0.70239426, 0.06890101],
       [0.86017059, 0.29248975, 0.45228854, 0.67307089, 0.3382637 ]])

In [74]:
q1

array([[0.92367514, 0.98537991, 0.92478601, 0.49088781],
       [0.97431609, 0.69345607, 0.3586684 , 0.33951068],
       [0.52281072, 0.59919183, 0.48338176, 0.4311844 ],
       [0.60681955, 0.70239426, 0.06890101, 0.86017059],
       [0.29248975, 0.45228854, 0.67307089, 0.3382637 ]])

In [83]:
q3 = q1[:2,:2].reshape(2,2)
q3

array([[0.92367514, 0.98537991],
       [0.97431609, 0.69345607]])

In [89]:
r = np.random.randint(1,10,(5,5))

In [90]:
r

array([[8, 2, 7, 8, 2],
       [6, 4, 2, 3, 3],
       [6, 1, 1, 8, 6],
       [9, 9, 3, 7, 2],
       [1, 7, 5, 7, 4]])

In [105]:
r[2:4,:3] += 1

In [106]:
r

array([[8, 2, 7, 8, 2],
       [6, 4, 2, 3, 3],
       [2, 2, 2, 8, 6],
       [2, 2, 2, 7, 2],
       [1, 7, 5, 7, 4]])

In [116]:
a = np.array([2,3,4])
a

array([2, 3, 4])

In [117]:
b = a * 3

In [118]:
a[1] = 10

In [119]:
b

array([ 6,  9, 12])

In [120]:
a

array([ 2, 10,  4])

In [121]:
b == a

array([False, False, False])

In [167]:
a = np.random.randint(1,100,(3,3))
b = np.random.randint(1,100,(3,3))
b[0,0] = 0

In [168]:
print(a)
print()
print(b)

[[16 23 21]
 [27 77 19]
 [10 53 19]]

[[ 0 35 89]
 [52 12 83]
 [56 28 41]]


In [169]:
a * b

array([[   0,  805, 1869],
       [1404,  924, 1577],
       [ 560, 1484,  779]])

In [170]:
a/b

/home/student/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[       inf, 0.65714286, 0.23595506],
       [0.51923077, 6.41666667, 0.22891566],
       [0.17857143, 1.89285714, 0.46341463]])

In [186]:
b = a**3

In [187]:
b

array([[64, 64, 64, 64, 64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64, 64, 64, 64, 64]])

In [188]:
np.sqrt(b)

array([[8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [189]:
np.sin(b)

array([[0.92002604, 0.92002604, 0.92002604, 0.92002604, 0.92002604,
        0.92002604, 0.92002604, 0.92002604, 0.92002604, 0.92002604],
       [0.92002604, 0.92002604, 0.92002604, 0.92002604, 0.92002604,
        0.92002604, 0.92002604, 0.92002604, 0.92002604, 0.92002604],
       [0.92002604, 0.92002604, 0.92002604, 0.92002604, 0.92002604,
        0.92002604, 0.92002604, 0.92002604, 0.92002604, 0.92002604],
       [0.92002604, 0.92002604, 0.92002604, 0.92002604, 0.92002604,
        0.92002604, 0.92002604, 0.92002604, 0.92002604, 0.92002604],
       [0.92002604, 0.92002604, 0.92002604, 0.92002604, 0.92002604,
        0.92002604, 0.92002604, 0.92002604, 0.92002604, 0.92002604],
       [0.92002604, 0.92002604, 0.92002604, 0.92002604, 0.92002604,
        0.92002604, 0.92002604, 0.92002604, 0.92002604, 0.92002604],
       [0.92002604, 0.92002604, 0.92002604, 0.92002604, 0.92002604,
        0.92002604, 0.92002604, 0.92002604, 0.92002604, 0.92002604],
       [0.92002604, 0.92002604, 0.9200260

In [192]:
np.concatenate([a,b], axis=1)

array([[ 4,  4,  4,  4,  4,  4,  4,  4,  4,  4, 64, 64, 64, 64, 64, 64,
        64, 64, 64, 64],
       [ 4,  4,  4,  4,  4,  4,  4,  4,  4,  4, 64, 64, 64, 64, 64, 64,
        64, 64, 64, 64],
       [ 4,  4,  4,  4,  4,  4,  4,  4,  4,  4, 64, 64, 64, 64, 64, 64,
        64, 64, 64, 64],
       [ 4,  4,  4,  4,  4,  4,  4,  4,  4,  4, 64, 64, 64, 64, 64, 64,
        64, 64, 64, 64],
       [ 4,  4,  4,  4,  4,  4,  4,  4,  4,  4, 64, 64, 64, 64, 64, 64,
        64, 64, 64, 64],
       [ 4,  4,  4,  4,  4,  4,  4,  4,  4,  4, 64, 64, 64, 64, 64, 64,
        64, 64, 64, 64],
       [ 4,  4,  4,  4,  4,  4,  4,  4,  4,  4, 64, 64, 64, 64, 64, 64,
        64, 64, 64, 64],
       [ 4,  4,  4,  4,  4,  4,  4,  4,  4,  4, 64, 64, 64, 64, 64, 64,
        64, 64, 64, 64],
       [ 4,  4,  4,  4,  4,  4,  4,  4,  4,  4, 64, 64, 64, 64, 64, 64,
        64, 64, 64, 64],
       [ 4,  4,  4,  4,  4,  4,  4,  4,  4,  4, 64, 64, 64, 64, 64, 64,
        64, 64, 64, 64]])

In [198]:
a = np.arange(50).reshape(5,-1)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [194]:
a

array([[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4]])

In [208]:
a[:,::-2]

array([[ 9,  7,  5,  3,  1],
       [19, 17, 15, 13, 11],
       [29, 27, 25, 23, 21],
       [39, 37, 35, 33, 31],
       [49, 47, 45, 43, 41]])

In [209]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [211]:
b = a * 2

In [213]:
np.hstack([a,b])

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9,  0,  2,  4,  6,  8, 10,
        12, 14, 16, 18],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 22, 24, 26, 28, 30,
        32, 34, 36, 38],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 40, 42, 44, 46, 48, 50,
        52, 54, 56, 58],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 60, 62, 64, 66, 68, 70,
        72, 74, 76, 78],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 80, 82, 84, 86, 88, 90,
        92, 94, 96, 98]])

In [214]:
np.tile(a,3)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9,  0,  1,  2,  3,  4,  5,
         6,  7,  8,  9,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 20, 21, 22, 23, 24, 25,
        26, 27, 28, 29, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 40, 41, 42, 43, 44, 45,
        46, 47, 48, 49, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [237]:
a = np.array([1,2,3,4,5])
b = np.array([4,2,6,4,8])
np.setdiff1d(a,b)

array([1, 3, 5])

In [238]:
a

array([1, 2, 3, 4, 5])

In [233]:
b

array([4, 5, 6, 7, 8])

In [239]:
c = np.where(a==b)

In [242]:
np.random.randn(10)

array([-1.37393003, -0.68832196, -0.18488891, -0.15620457, -0.75973696,
       -1.24538775, -0.80338425, -0.05242566,  0.52164124,  1.55833238])